services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user_barber
      POSTGRES_PASSWORD: password_barber
      POSTGRES_DB: barbershop_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user_barber:password_barber@db:5432/barbershop_db

volumes:
  pgdata: